services:
  bot:
    build: .
    container_name: test-bot
    env_file:
      - .env
    restart: unless-stopped
    command: ["npm", "start"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s